// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Ds_ZzypSF6A8AYDkAWKamoMpaNXm3UA',
    appId: '1:614613307153:web:8bcee32095af81582346b0',
    messagingSenderId: '614613307153',
    projectId: 'scholar-app-3726f',
    authDomain: 'scholar-app-3726f.firebaseapp.com',
    storageBucket: 'scholar-app-3726f.firebasestorage.app',
    measurementId: 'G-H5LVWNDKK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMFD7hD94MbgehFxCSq9RFd62SKntNEEA',
    appId: '1:614613307153:android:f3ae43ed9b8e99d02346b0',
    messagingSenderId: '614613307153',
    projectId: 'scholar-app-3726f',
    storageBucket: 'scholar-app-3726f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQdLiBZ4fDB2ijHAHJ6gTIwPkEQhlV4RM',
    appId: '1:614613307153:ios:67aef98fc0fef4c72346b0',
    messagingSenderId: '614613307153',
    projectId: 'scholar-app-3726f',
    storageBucket: 'scholar-app-3726f.firebasestorage.app',
    iosBundleId: 'com.example.scholarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQdLiBZ4fDB2ijHAHJ6gTIwPkEQhlV4RM',
    appId: '1:614613307153:ios:67aef98fc0fef4c72346b0',
    messagingSenderId: '614613307153',
    projectId: 'scholar-app-3726f',
    storageBucket: 'scholar-app-3726f.firebasestorage.app',
    iosBundleId: 'com.example.scholarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Ds_ZzypSF6A8AYDkAWKamoMpaNXm3UA',
    appId: '1:614613307153:web:41aeb92408d96c042346b0',
    messagingSenderId: '614613307153',
    projectId: 'scholar-app-3726f',
    authDomain: 'scholar-app-3726f.firebaseapp.com',
    storageBucket: 'scholar-app-3726f.firebasestorage.app',
    measurementId: 'G-CTCDPMDL43',
  );
}
